### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by russellbanks** [MayakaApps/ComposeWindowStyler#12]
As I can see, using GitHub Maven packages requires authentication which just makes installing the packages and building in workflows more difficult. It would be good if it were published to other sources instead/too (such as Maven Central)?

**Comment by MSDarwish2000** [comment]
Thank you for your feedback. I'll start the process of publishing it to the Maven Central.

**Comment by MSDarwish2000** [comment]
The latest version is now available on Maven Central, so it can easily added without adding additional repositories.

Sample Code:
`implementation("com.mayakapps.compose:window-styler:<latest-version>")`
