### ISSUE TITLE
Add WindowScope extension function for WindowStyle

### ISSUE THREAD

**Issue by russellbanks** [MayakaApps/ComposeWindowStyler#15]
Currently, WindowStyle uses [FrameWindowScope](https://github.com/MayakaApps/ComposeWindowStyler/blob/2c4e52472516fe34c5b5fb24d3ce6c11f1a45535/window-styler/src/jvmMain/kotlin/com/mayakapps/compose/windowstyler/WindowStyle.kt). However, for third-party window libraries, such as [Aurora](https://github.com/kirill-grouchnikov/aurora) (the one I use in my app), they have their own scopes that extend WindowScope. Therefore, to work around this, I have created an extension function that works for me:

```kt
@Composable
private fun WindowScope.WindowStyle(isDarkTheme: Boolean, backdropType: WindowBackdrop = WindowBackdrop.Mica) {
    val manager = remember { WindowManager(window as JFrame, isDarkTheme, backdropType) }

    LaunchedEffect(isDarkTheme) {
        manager.isDarkTheme = isDarkTheme
    }

    LaunchedEffect(backdropType) {
        manager.backdropType = backdropType
    }
}
```

Could this be included in the library itself? As it extends WindowScope rather than any third-party scope, I think it's generic enough to use it as a second extension function, for use cases like this.

The only difference with the two functions should be that this one uses WindowScope rather than FrameWindowScope and that the window in `WindowManager` is cast to `JFrame`.

**Comment by MSDarwish2000** [comment]
I agree with you that the function receiver should be as generic as possible for versatility. I'll be updating that soon.
