### ISSUE TITLE
Mica backdrop icons have incorrect colours when changing theme

### ISSUE THREAD

**Issue by russellbanks** [MayakaApps/ComposeWindowStyler#23]
**Describe the bug**
Changing the theme whilst using the Mica window backdrop makes the action buttons the incorrect colour, until the window is moved or activated by pressing those buttons.

![java_4CzhAp6VN1](https://user-images.githubusercontent.com/74878137/174146166-bd32e041-e083-4faf-a70a-6fc2ff1d18d7.gif)

**To Reproduce**
1. Set WindowBackdrop to Mica
2. Change the theme

**Expected behavior**
The icons should mimic the theme correctly (white icons on dark, black icons on light, etc).

**Screenshots**

https://user-images.githubusercontent.com/74878137/174146162-9c24256d-9165-4cef-b1fe-f6eeba06f1e0.mp4

**OS (please complete the following information):**
 - OS: Windows 11
 - Build: 22000

**Additional context**
This is also present in the demo app.

**Comment by MSDarwish2000** [comment]
Thank you for adopting the library in your project and your continuous feedback. As you may have already noticed that I've just released a hotfix release.
